### ISSUE TITLE
使用 AES256 打包的固件，在升级时出现 HASH 校验失败

### ISSUE THREAD

**Issue by cyberxnomad** [RT-Thread-packages/ota_downloader#11]
在 iot.rt-thread.org 生成的 bootloader，勾选了固件 AES256 加密 + 固件压缩(gzip)，固件打包器也选择了 gzip 与 AES256，密钥和 IV 与网页端生成 bootloader 时填写的一致。

![image](https://user-images.githubusercontent.com/18170226/97539767-8264da80-19fd-11eb-8436-2559694f25e8.png)

如果 bootloader 不使用 AES，打包也不勾选 AES，升级是正常的。

**Comment by lazyguoguo** [comment]
![image](https://user-images.githubusercontent.com/18182838/121307096-37675a00-c932-11eb-9e0a-024ce8af07df.png)
![image](https://user-images.githubusercontent.com/18182838/121307199-55cd5580-c932-11eb-8fc2-b55123a7445a.png)
新版本 raw_crc 计算有问题？ 还是rbl包头 已经更新一些参数？

**Comment by aozima** [comment]
你用这个贴子里面的命令行版本的打包软件试试。
如你怀疑的那样，这里不压缩不加密，但CRC不一样的，应该是对齐规则不同造成的。

**Comment by cyberxnomad** [comment]
> 你用这个贴子里面的命令行版本的打包软件试试。
> 如你怀疑的那样，这里不压缩不加密，但CRC不一样的，应该是对齐规则不同造成的。

这个 repo 下面只有2年前 commit 的打包软件呀，命令行的和楼上的新版的不知在哪下载

**Comment by aozima** [comment]
抱歉链接漏掉了，现在直接上传到github了。

打包工具有命令行版本
[rt_ota_packaging_tool.cmd.20200517.zip](https://github.com/RT-Thread-packages/ota_downloader/files/6622669/rt_ota_packaging_tool.cmd.20200517.zip)
