### ISSUE TITLE
quicklz压缩尺寸问题

### ISSUE THREAD

**Issue by RichardWei** [RT-Thread-packages/ota_downloader#19]
您好
使用quicklz网站下载的c#，demo程序，压缩后，和官方打包器压缩后的的尺寸不一样，理论上大小应该只差96个字节，我使用的也是quicklz150_32_3.dll这个dll文件，我是哪里疏忽了.
![微信截图_20220218154304](https://user-images.githubusercontent.com/8604191/154639821-7887c05d-8bf1-4915-b2d7-0bbd8d75d61c.png)
![微信截图_20220218154434](https://user-images.githubusercontent.com/8604191/154639839-06626abf-8788-4981-b13c-e152cc565fd5.png)

**Comment by aozima** [comment]
压缩级别调下试试，不过lz都压缩率不高，推荐使用gzip或是lzma，压缩比喜人。

**Comment by RichardWei** [comment]
好的，谢谢，我试下

**Comment by RichardWei** [comment]
用了gzip，压缩比喜人，参考了网友的python版本
