### ISSUE TITLE
什么时候能支持linux下命令行操作？

### ISSUE THREAD

**Issue by Werner42** [RT-Thread-packages/ota_downloader#21]

**Comment by mysterywolf** [comment]
你是说ota？还是env？

**Comment by zdima** [comment]
I think it means a command line tool for linux to package the elf file for OTA upload.
It would be beneficial for community to have access to source code of .Net packager, and perhaps someone will create Linux version.

**Comment by 209jkjkjk** [comment]
https://github.com/RT-Thread/W601_IoT_Board/tree/master/tools/ota_packager
我没试过，但这个仓库里的 cli会不会就是linux下的
