### ISSUE TITLE
Ymodem下载固件受影响导致失败

### ISSUE THREAD

**Issue by ZHANGHSING** [RT-Thread-packages/ota_downloader#6]
超级终端：SecureCRT

if (!rym_recv_on_device(&rctx, rt_console_get_device(), RT_DEVICE_OFLAG_RDWR | RT_DEVICE_FLAG_INT_RX, ymodem_on_begin, ymodem_on_data, NULL, RT_TICK_PER_SECOND))

在这个操作时间内，rt_kprintf输出信息，下载就会出现错误并中断升级，是否可以考虑忽略rt_kprintf输出呢？

**Comment by armink** [comment]
日志打印建议使用 LOG_X 日志 API ，这样会好处理一些，rt_kprintf 本身就是往控制台输出的 API ，不建议用作日志显示

**Comment by ZHANGHSING** [comment]
> 日志打印建议使用 LOG_X 日志 API ，这样会好处理一些，rt_kprintf 本身就是往控制台输出的 API ，不建议用作日志显示

因为这个比较特殊，LOG_X同样也会使用rt_kprintf，同时保存在外部flash需要一定时间。我是想后面更新时能不能在固件传输时暂停rt_kprintf信息输出，保证下载的稳定性。这个想法我验证是可行的

**Comment by armink** [comment]
用了 LOG_X 就可以使用 ulog 的日志开关 API ，在传输时，停止日志输出

**Comment by ZHANGHSING** [comment]
> 用了 LOG_X 就可以使用 ulog 的日志开关 API ，在传输时，停止日志输出

好的，明白了，这样也是可行的方法
