### ISSUE TITLE
打包工具建议提供一个命令行版本

### ISSUE THREAD

**Issue by wq807319473** [RT-Thread-packages/ota_downloader#9]
有些 CPU 不方便使用工具直接下载。 
开发过程中，OTA 下载是个不错的选项。
图形界面无法集成到  .bat 做自动化处理。

**Comment by armink** [comment]
什么 MCU 呢？

**Comment by wq807319473** [comment]
F1C100S

**Comment by aozima** [comment]
打包工具有命令行版本
[rt_ota_packaging_tool.cmd.20200517.zip](https://github.com/RT-Thread-packages/ota_downloader/files/6622669/rt_ota_packaging_tool.cmd.20200517.zip)
